/**
 * LARPABLE — Legal Content Filter
 * Automatically removes PolicyGen disclaimers and similar boilerplate
 * from fetched legal document HTML before rendering.
 */
(function () {
  'use strict';

  // Patterns that indicate a disclaimer paragraph to remove
  const DISCLAIMER_PATTERNS = [
    /PolicyGen/gi,
    /informational purposes only/gi,
    /does not constitute legal advice/gi,
    /consult with a qualified attorney/gi,
    /generated by.*for informational/gi
  ];

  /**
   * Clean legal HTML by removing disclaimer content.
   * Works by parsing the HTML into a DOM fragment, walking the tree,
   * and removing elements that match disclaimer patterns.
   * Also strips trailing <hr> elements that precede disclaimers.
   */
  window.legalFilterClean = function (html) {
    const div = document.createElement('div');
    div.innerHTML = html;

    // Walk all <p> and <em> elements and check for disclaimer text
    const toRemove = [];
    const allElements = div.querySelectorAll('p, em, hr');

    let hrBeforeDisclaimer = null;

    allElements.forEach(el => {
      const text = el.textContent || '';
      const isDisclaimer = DISCLAIMER_PATTERNS.some(p => p.test(text));

      if (isDisclaimer) {
        // Remove this element
        toRemove.push(el);
        // Also remove any preceding <hr>
        if (hrBeforeDisclaimer) {
          toRemove.push(hrBeforeDisclaimer);
        }
      }

      if (el.tagName === 'HR') {
        // Tentatively mark this HR — if the next sibling is a disclaimer, remove it too
        hrBeforeDisclaimer = el;
      } else if (el.tagName === 'P') {
        if (!isDisclaimer) {
          hrBeforeDisclaimer = null; // Reset — this P is real content
        }
      }
    });

    // Also scan for text nodes that might contain the disclaimer wrapped in different tags
    // Handle the case where the whole trailing block is:
    // <hr><p><em>...PolicyGen...</em></p>
    const allP = div.querySelectorAll('p');
    allP.forEach(p => {
      const text = (p.textContent || '').trim();
      if (DISCLAIMER_PATTERNS.some(pattern => pattern.test(text))) {
        if (!toRemove.includes(p)) toRemove.push(p);
      }
    });

    // Remove all flagged elements
    toRemove.forEach(el => {
      if (el.parentNode) el.parentNode.removeChild(el);
    });

    // Clean up any trailing <hr> that's now the last child (likely the separator before the removed disclaimer)
    let lastChild = div.lastElementChild;
    while (lastChild && lastChild.tagName === 'HR') {
      const prev = lastChild.previousElementSibling;
      div.removeChild(lastChild);
      lastChild = prev;
    }

    return div.innerHTML;
  };
})();
